[package]
name = "gd_launcher_test"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "gd_launcher_test"

[dependencies]
android-activity = { version = "0.6", features = ["native-activity"] }
android_logger = "0.15"
log = "0.4"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
