plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gdlauncher.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.gdlauncher.app"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation 'androidx.games:games-activity:3.0.5'
    
    // Menambahkan pustaka wajib pelengkap GameActivity agar tidak eror OnApplyWindowInsetsListener
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
}
